/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/airplane/model.glb
Dog in plane by Nikki Morin [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/6Y6MQye_n1h)
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

const HELIX_SPEED = 6;

export function Airplane(props) {
  const { nodes, materials } = useGLTF("./models/airplane/model.glb");

  const helix = useRef();

  useFrame((_state, delta) => {
    helix.current.rotation.x += delta * HELIX_SPEED;
  });

  return (
    <group {...props} dispose={null}>
      <group
        rotation-y={[(Math.PI / 1.5) * 2.5]}
        position={[-0.05, 0.03, -0.01]}
      >
        <mesh
          geometry={nodes["Node-Mesh"].geometry}
          material={materials.mat7}
        />
        <mesh
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.mat23}
        />
        <mesh
          geometry={nodes["Node-Mesh_2"].geometry}
          material={materials.mat21}
        />
        <mesh
          geometry={nodes["Node-Mesh_3"].geometry}
          material={materials.mat19}
        />
      </group>
      <mesh
        ref={helix}
        geometry={nodes.helix.geometry}
        material={materials.mat15}
        position={[0.23, -0.35, 0.06]}
      />
    </group>
  );
}

useGLTF.preload("./models/airplane/model.glb");
